name: build-docs

on:
  # 当推送到默认分支时触发
  push:
    branches: ["master"]

  # 允许手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 仅允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: 安装依赖
        run: npm install
      - name: 构建 Docs
        run: npm run docs:build
      - name: 上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-dist
          path: docs/.vuepress/dist

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 保存构建产物
        uses: actions/download-artifact@v2
        with:
          name: vuepress-dist
          path: dist
      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v2
